### ISSUE TITLE
请问这个数据库是使用的mysql还是redis呢

### ISSUE THREAD

**Issue by xixixixi1230** [Yin-Hongwei/music-website#304]
请问这个数据库是使用的mysql还是redis呢，我将sql文件导入mysql，启动redis服务，username和password写的mysql的用户名和密码，报错了

**Comment by aryangzhu** [comment]
```
spring.datasource.url=jdbc:mysql://localhost:3306/tp_music?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 
```
从配置文件中可以看出使用的是MySQL,你要将报错信息粘贴出来这样大家才能准确定位问题

**Comment by aryangzhu** [comment]
我忘了代码，推测一下哈，MySQL是作为DB存储来使用，Redis是作为存储来使用。你可以先找个docker教程将mysql和redis分别启动，然后将项目中的配置文件和自己docker的容器配置做比较进行替换
![image](https://github.com/user-attachments/assets/f2778330-48ee-423e-abc8-8e13c171e715)
```
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_learning?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
```
